name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { tag: "latest", version: "17", repo: "edge" }
          - { tag: "16", version: "16", repo: "edge" }
          - { tag: "15", version: "15", repo: "edge" }
          - { tag: "13", version: "13", repo: "v3.16" }
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v3
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nmch/pg2s3:${{ matrix.tag }}
          build-args: |
            REPO_VERSION=${{ matrix.repo }}
            POSTGRES_VERSION=${{ matrix.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
